#ifndef ERRORS_SENTRY
#define ERRORS_SENTRY


using err_code = int;
enum ERRORS : err_code {
    NO_ERROR,
    INIT_FAIL,
    INIT_IMAGE_FAIL,
    WIN_CREATE_FAIL,
    RENDERER_CREATE_FAIL,
    SCREEN_CREATION_FAIL,
    EXIT_HANDLER_REG_FAIL,

    MAP_NOT_LOADED,
    MAP_FILE_NOT_OPENED,
    MAP_WRONG_DIMENSIONS,

    TILEMAP_NOT_LOADED,
    TILEMAP_WRONG_PIXEL_SIZE,
    TILEMAP_NO_PIXELS_GOT,
    TILEMAP_CANNOT_CONVERT_PIXELS,
    TILEMAP_CANNOT_SET_COLOR_KEY,
};


#endif
